In [2]:
import numpy as np
from pandas import Series, DataFrame
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

# Import "modules"

In [3]:
df_sample = pd.read_csv('C://Users//snuist//Data//Lending_Club_Data_Subsample.csv')

X_inc = df_sample[['annual_inc']].as_matrix()
y = df_sample[['bad']].as_matrix()

In [4]:
X_inc.shape

(1000, 1)

In [5]:
y.shape

(1000, 1)

In [6]:
X1 = np.array([1, 1.3, 2, 4])

for ii in X1:
    print(ii)    

1.0
1.3
2.0
4.0


In [7]:
1*(X1 > 2)

array([0, 0, 0, 1])

In [12]:
v1 = np.array([[1, 2, 3, 4]]).T
np.concatenate((v1, v1), axis=1)

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [9]:
mdl_OLS = linear_model.LinearRegression()

In [13]:
# np.percentile(array, )
inc_min = np.percentile(X_inc, 10)
inc_min

30000.0

In [16]:
inc_max = np.percentile(X_inc, 90)
inc_max

116550.00000000001

In [16]:
grid_num = 10

inc_grid = np.linspace(inc_min, inc_max, grid_num)
inc_grid

array([  30000.        ,   39616.66666667,   49233.33333333,
         58850.        ,   68466.66666667,   78083.33333333,
         87700.        ,   97316.66666667,  106933.33333333,  116550.        ])

In [18]:
MSE_record = np.zeros(grid_num)
ii = 0

for r in inc_grid:
    ind_mat = 1 * (X_inc > r)
    X_aug = np.concatenate((X_inc, ind_mat, X_inc*ind_mat), axis = 1)

    mdl_OLS.fit(X_aug, y)
    y_hat = mdl_OLS.predict(X_aug)
    
    MSE_record[ii] = np.mean((y - y_hat)**2)
    ii = ii + 1

array([ 0.11393225,  0.11355832,  0.11336623,  0.11338519,  0.1132023 ,
        0.1133684 ,  0.11377309,  0.11356826,  0.11360405,  0.11383134])

In [19]:
argmin_ii = np.argmin(MSE_record)
argmin_ii

4

In [20]:
r_hat = inc_grid[argmin_ii]
r_hat

68466.666666666672

In [21]:
ind_mat = 1 * (X_inc > r_hat)
X_aug = np.concatenate((X_inc, ind_mat, X_inc*ind_mat), axis = 1)

mdl_OLS.fit(X_aug, y)
mdl_OLS.coef_

array([[ -3.33191211e-06,  -1.65910466e-01,   3.25378643e-06]])