In [2]:
import numpy as np
from pandas import Series, DataFrame
import pandas as pd
import matplotlib.pyplot as plt

# Import modules

In [3]:
df_sample = pd.read_csv('C://Users//snuist//Data//Lending_Club_Data_Subsample.csv')
print(df_sample.head())

   bad  purpose_1  purpose_2  purpose_3  purpose_4  purpose_5  term_1  term_2  \
0    0          1          0          0          0          0       1       0   
1    0          0          1          0          0          0       1       0   
2    0          1          0          0          0          0       1       0   
3    0          1          0          0          0          0       1       0   
4    0          1          0          0          0          0       1       0   

   verification_status_1  verification_status_2    ...            dti  \
0                      1                      0    ...      11.910000   
1                      0                      0    ...      11.140000   
2                      0                      1    ...      12.990000   
3                      0                      0    ...      30.620001   
4                      1                      0    ...       6.830000   

   delinq_2yrs  inq_last_6mths  open_acc  pub_rec  total_acc  \
0         

In [4]:
list(df_sample)

['bad',
 'purpose_1',
 'purpose_2',
 'purpose_3',
 'purpose_4',
 'purpose_5',
 'term_1',
 'term_2',
 'verification_status_1',
 'verification_status_2',
 'verification_status_3',
 'initial_list_status_1',
 'initial_list_status_2',
 'loan_amnt',
 'installment',
 'annual_inc',
 'dti',
 'delinq_2yrs',
 'inq_last_6mths',
 'open_acc',
 'pub_rec',
 'total_acc',
 'pub_rec_bankruptcies',
 'emp_length',
 'pop',
 'urate']

In [23]:
df_X = df_sample.iloc[:, 1:26].as_matrix()
df_y = df_sample[['bad']].as_matrix()

df_X = np.delete(df_X, [4, 6, 8, 11], axis = 1)
#Exclude some variables to prevent perfect multicolinearity

In [24]:
[X_train, X_test] = np.split(df_X, [800], axis = 0)

In [25]:
X_train.shape

(800, 21)

In [26]:
X_test.shape

(200, 21)

In [27]:
[y_train, y_test] = np.split(df_y, [800], axis = 0)
y_train.shape

(800, 1)

In [28]:
mdl_OLS = linear_model.LinearRegression()
mdl_OLS.fit(X_train, y_train)
mdl_OLS.coef_

array([[ -4.86214098e-02,  -1.23258977e-02,  -8.51268142e-02,
          7.75283996e-01,   7.38612750e-03,  -4.07718445e-02,
          3.12913579e-02,   3.06045379e-02,   9.74744205e-06,
         -2.83940208e-04,  -2.56287361e-07,   1.69647659e-03,
         -3.22204404e-03,   2.20679767e-02,   1.04964671e-03,
         -1.29939896e-01,  -9.12059323e-05,   1.94849379e-01,
         -1.85217913e-03,   7.10182052e-11,   2.27926607e-03]])

In [29]:
mdl_Lasso = linear_model.Lasso(alpha = 10**(-3))
mdl_Lasso.fit(X_train, y_train)
mdl_Lasso.coef_

array([ -3.63497945e-02,  -0.00000000e+00,  -6.85218763e-02,
         0.00000000e+00,   0.00000000e+00,  -3.60476628e-02,
         2.62251536e-02,   2.01470687e-02,   8.37870073e-06,
        -2.50765146e-04,  -2.23347202e-07,   1.78194272e-03,
        -2.92735535e-03,   2.39529579e-02,   6.42417903e-04,
        -1.77160430e-02,   1.46132782e-04,   5.67137194e-02,
        -1.80729516e-03,   7.18555884e-11,   2.65824594e-03])

In [30]:
y_in_OLS = mdl_OLS.predict(X_train)
np.mean((y_train - y_in_OLS)**2) # In-sample fit of OLS (MSE)

0.10682318582011313

In [31]:
y_in_Lasso = mdl_Lasso.predict(X_train)[:, np.newaxis]
np.mean((y_train - y_in_Lasso)**2) # In-sample fit of Lasso (MSE)

0.11403042285779001

In [32]:
y_out_OLS = mdl_OLS.predict(X_test)
np.mean((y_test - y_out_OLS)**2) # Out-of-sample fit of OLS (MSE)

0.1254510778341712

In [33]:
y_out_Lasso = mdl_Lasso.predict(X_test)[:, np.newaxis]
np.mean((y_test - y_out_Lasso)**2) # Out-of-sample fit of Lasso (MSE)

# cf.) Less MSE is better

0.12451793198427577

In [34]:
# Why we have to use [:, np.newaxis]? Consider the following example.

v1 = np.array([[1, 2, 3, 4]]).T
v2 = np.array([0, 1, 0, 1]).T
v3 = v2[np.newaxis, :].T

print(v1, v1.shape); print()
print(v2, v2.shape); print()
print(v3, v3.shape); print()

print("(v1 - v2) = \n", v1 - v2); print()
print("(v1 - v3) = \n", v1 - v3); print()

# To obtain the result that is "natural" to us, we need to adjust dimensions using np.newaxis

[[1]
 [2]
 [3]
 [4]] (4, 1)

[0 1 0 1] (4,)

[[0]
 [1]
 [0]
 [1]] (4, 1)

(v1 - v2) = 
 [[1 0 1 0]
 [2 1 2 1]
 [3 2 3 2]
 [4 3 4 3]]

(v1 - v3) = 
 [[1]
 [1]
 [3]
 [3]]

